name: presence
version: 0.1.0
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  get: 4.6.5
  firebase_core: 2.15.1
  firebase_auth: 4.6.3
  cloud_firestore: 4.9.1
  firebase_storage: 11.2.3
  image_picker: 0.8.9
  convex_bottom_bar: 3.2.0
  intl: 0.18.1
  geolocator: 9.0.2
  geocoding: 2.1.0
  syncfusion_flutter_datepicker: 22.1.38
  flutter:
    sdk: flutter
  flutter_login: ^4.2.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

dev_dependencies:
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  # Background color of splash screen
  color: "#ffffff"
  # Image that you want to show
  image: assets/logoSplash.png
  # Sizing of image
  fill: true
  # Splash Image to show in dark mode (Optional)
  image_dark: assets/logoSplash.png
  # Background color of dark mode (Optional)
  color_dark: "#000000"

flutter:
  uses-material-design: true
  assets:
    - assets/
